import Hero from '@/components/Hero'
import MainLayout from '@/components/Layouts/MainLayout'
import Head from 'next/head'
import logo from './../../public/logo.png'
import AllProducts from '@/components/Products/AllProducts'
export default function Home() {
  return (
    <>
      <Head>
        <title>Quantum Byte</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={logo} />
      </Head>
      {/* <Hero/> */}
      <AllProducts/>
    </>
  )
}

Home.getLayout = function getLayout(page){
  return <MainLayout>{page}</MainLayout>
}