import Hero from '@/components/Hero'
import MainLayout from '@/components/Layouts/MainLayout'
import AllProducts from '@/components/Products/allProducts'
import Head from 'next/head'
// import logo from './../assets/logo.png'
export default function Home() {
  return (
    <>
      <Head>
        <title>Quantum Byte</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      {/* <Hero/> */}
      <AllProducts/>
    </>
  )
}

Home.getLayout = function getLayout(page){
  return <MainLayout>{page}</MainLayout>
}