import Head from 'next/head'
// import logo from './../assets/logo.png'
export default function Home() {
  return (
    <>
      <Head>
        <title>Quantum Byte</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <h1>Project setup ready</h1>
    </>
  )
}
